"""Add rating and rating_count columns to Game

Revision ID: 39651f5df930
Revises: 
Create Date: 2024-03-08 13:03:45.403583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39651f5df930'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apk_size', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('cache_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['cache_name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_subscribed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('reg_date', sa.DateTime(timezone=150), nullable=True))
        batch_op.create_unique_constraint(None, ['avatar_path'])
        batch_op.create_unique_constraint(None, ['nickname'])
        batch_op.create_unique_constraint(None, ['reg_date'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reg_date')
        batch_op.drop_column('avatar_path')
        batch_op.drop_column('is_subscribed')
        batch_op.drop_column('nickname')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('cache_size')
        batch_op.drop_column('apk_size')

    op.drop_table('comment')
    # ### end Alembic commands ###
