"""Update User table

Revision ID: 96134eeb6539
Revises: 39651f5df930
Create Date: 2024-03-08 13:12:15.126087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96134eeb6539'
down_revision: Union[str, None] = '39651f5df930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
        batch_op.alter_column('rating_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_subscribed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('reg_date', sa.DateTime(timezone=150), nullable=True))
        batch_op.create_unique_constraint(None, ['nickname'])
        batch_op.create_unique_constraint(None, ['reg_date'])
        batch_op.create_unique_constraint(None, ['avatar_path'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reg_date')
        batch_op.drop_column('avatar_path')
        batch_op.drop_column('is_subscribed')
        batch_op.drop_column('nickname')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('rating_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))

    # ### end Alembic commands ###
