"""Add last_changed column to Game model

Revision ID: 8dbcacd7e012
Revises: 02c690b0d4ef
Create Date: 2024-05-24 20:29:02.474706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbcacd7e012'
down_revision = '02c690b0d4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_changed', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('last_changed')

    # ### end Alembic commands ###
