"""Add date to Comment model

Revision ID: 9e3a623f81bb
Revises: 2a63d6676ae5
Create Date: 2024-04-28 10:11:30.242875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e3a623f81bb'
down_revision = '2a63d6676ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
        batch_op.alter_column('rating_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('reg_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('reg_date',
               existing_type=sa.DateTime(timezone=150),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('rating_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
