"""Rename 'nickname' column in User to 'username'

Revision ID: f1249a3d9f44
Revises: 4c4baef72496
Create Date: 2024-04-28 11:48:41.465244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1249a3d9f44'
down_revision = '4c4baef72496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('user_nickname_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_nickname_key', ['nickname'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###
